---
- name: Install corosync-qnetd package
  ansible.builtin.apt:
    name:
      - corosync-qnetd
      - corosync-qdevice
    state: present
  when: ansible_facts['os_family'] == "Debian" and not ansible_check_mode

- name: Ensure corosync-qnetd service enabled
  ansible.builtin.service:
    name: corosync-qnetd
    state: started
    enabled: true
  when: ansible_facts['os_family'] == "Debian" and not ansible_check_mode
